[project]
name = "kiba-build"
version = "0.1.10"
description = "Kiba Labs' python building and testing utilities"
readme = "README.md"
requires-python = ">=3.11, <4"
dependencies = [
    "asyncclick~=8.3.0",
    "bandit~=1.9.4",
    "bump-my-version~=1.3.0",
    "mypy~=2.1.0",
    "pytest~=9.0.3",
    "pytest-asyncio~=1.3.0",
    "pytest-json-report~=1.5.0",
    "ruff~=0.15.14",
    "simple-chalk~=0.1.0",
    "twine~=6.2.0",
    "ty~=0.0.39",
    "wheel~=0.47.0",
]

[project.urls]
repository = "https://github.com/kibalabs/build-py"

[project.scripts]
lint-check = "buildpy.lint_check:run"
type-check = "buildpy.type_check:run"
security-check = "buildpy.security_check:run"
version = "buildpy.version:run"
test-check = "buildpy.test_check:run"

[tool.uv]
package = true

[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
core = ["/py.typed", "**/pyproject.toml"]
