select = [
    "I", # isort
    "E", # pycodestyle
    "F", # Pyflakes
    "W", # pycodestyle
    "N", # pep8-naming
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "PGH", # pygrep-hooks
    "PLC", # pylint
    "PLE", # pylint
    "PLR", # pylint
    "PLW", # pylint
    "S", # flake8-bandit
    "SIM", # flake8-simplify
    "T10", # flake8-debugger
    # "UP", # pyupgrade
    "RUF100",  # yesqa
]
ignore = [
    "E501", # line-too-long
    "F541", # f-string-missing-placeholders
    "TRY003", # raise-vanilla-args
    "S105", # hardcoded-password-string
    "S106", # hardcoded-password-func-arg
    "S107", # hardcoded-password-default
    "PLR0911", # too-many-return-statements
    "PLR0912", # too-many-branches
    "PLR0913", # too-many-arguments
    "PLR0915", # too-many-statements
    "UP006", # deprecated-collection-type"
    "UP007", # typing-union
    "B904", # raise-without-from-inside-except
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
# fixable = ["A", "B", "C", "D", "E", "F", "I"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py310"

[isort]
force-single-line = true
