name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy-package-next:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: package
      UV_PUBLISH_TOKEN: ${{ secrets.PYPI_PUBLISH_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          # NOTE(krishan711): need full history to calculate difference
          fetch-depth: 0
      - name: Build docker image
        run: docker build --tag $DOCKER_IMAGE .
      - name: Create .pypirc file
        run: echo -e "[pypi]\nusername=__token__\npassword=$PYPI_TOKEN" > .pypirc
      - name: Publish next package to pypi
        run: |
          docker run -v $(pwd)/.pypirc:/root/.pypirc $DOCKER_IMAGE /bin/bash -c " \
            && make publish \
          "
