name: Build
on:
  pull_request:
    branches: [ '*' ]
jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: buildpy
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --tag $DOCKER_IMAGE .
    - name: Run linting
      run: |
        docker run --name linting $DOCKER_IMAGE python buildpy/lint.py --directory buildpy --output-file linting-results.json --output-format annotations
        docker cp linting:/app/linting-results.json ./linting-results.json
    - name: Upload build linting results
      uses: kibalabs/github-action-create-annotations@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        json-file-path: ./linting-results.json
        check-name: lint-package
        fail-on-error: false
    - name: Run typing
      run: |
        docker run --name typing $DOCKER_IMAGE python buildpy/type_check.py --directory buildpy --output-file typing-results.json --output-format annotations
        docker cp typing:/app/typing-results.json ./typing-results.json
    - name: Upload build typing results
      uses: kibalabs/github-action-create-annotations@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        json-file-path: ./typing-results.json
        check-name: type-package
        fail-on-error: false
