name: Build
on:
  pull_request:
    branches: [ '*' ]
jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: buildpy
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --tag $DOCKER_IMAGE .
    - name: Run lint
      run: |
        docker run --name lint $DOCKER_IMAGE lint --directory buildpy --output-file lint-results.json --output-format annotations
        docker cp lint:/app/lint-results.json ./lint-results.json
    - name: Upload build lint results
      uses: kibalabs/github-action-create-annotations@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        json-file-path: ./lint-results.json
        check-name: lint-package
        fail-on-error: false
    - name: Run type-check
      run: |
        docker run --name type-check $DOCKER_IMAGE type-check --directory buildpy --output-file type-check-results.json --output-format annotations
        docker cp type-check:/app/type-check-results.json ./type-check-results.json
    - name: Upload build type-check results
      uses: kibalabs/github-action-create-annotations@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        json-file-path: ./type-check-results.json
        check-name: type-package
        fail-on-error: false
    - name: Run security-check
      run: |
        docker run --name security-check $DOCKER_IMAGE security-check --directory buildpy --output-file security-check-results.json --output-format annotations
        docker cp security-check:/app/security-check-results.json ./security-check-results.json
    - name: Upload build security-check results
      uses: kibalabs/github-action-create-annotations@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        json-file-path: ./security-results.json
        check-name: security-package
        fail-on-error: false
